// src/app/modules/auth/components/teacher-login/teacher-login.component.ts
import { Component, ViewEncapsulation } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule, FormBuilder, FormGroup, Validators } from '@angular/forms';
import { Router } from '@angular/router';
import { AuthService } from '../../services/auth.service';

type LoginMethodType = 'email' | 'school' | 'phone' | 'google';

@Component({
  selector: 'app-teacher-login',
  standalone: true,
  imports: [CommonModule, FormsModule, ReactiveFormsModule],
  templateUrl: './teacher-login.component.html',
  styleUrls: ['./teacher-login.component.scss'],
  encapsulation: ViewEncapsulation.None
})
export class TeacherLoginComponent {
  loginForm: FormGroup;
  twoFactorForm: FormGroup;
  showTwoFactor = false;
  multiDeviceAlert = false;
  isLoading = false;
  showPassword = false;
  errorMessage = '';
  loginMethod: LoginMethodType = 'email';

  loginMethods = [
    { id: 'email' as const, label: 'Email' },
    { id: 'school' as const, label: 'School ID' },
    { id: 'phone' as const, label: 'Phone' },
    { id: 'google' as const, label: 'Google' }
  ];

  constructor(
    private fb: FormBuilder,
    private router: Router,
    private authService: AuthService
  ) {
    this.loginForm = this.fb.group({
      email: ['', [Validators.email]],
      password: ['', [Validators.minLength(8)]],
      schoolId: [''],
      phone: ['']
    });

    this.twoFactorForm = this.fb.group({
      code: ['', [Validators.required, Validators.pattern('^[0-9]{6}$')]]
    });
  }

  goBack() {
    window.history.back();
  }

  onSubmit() {
    if (this.loginForm.valid) {
      this.isLoading = true;
      this.errorMessage = '';
      
      try {
        // Handle different login methods
        switch (this.loginMethod) {
          case 'email':
            this.handleEmailLogin();
            break;
          case 'school':
            this.handleSchoolLogin();
            break;
          case 'phone':
            this.handlePhoneLogin();
            break;
          case 'google':
            this.loginWithGoogle();
            break;
        }
      } catch (error) {
        this.errorMessage = 'Login failed. Please try again.';
        this.isLoading = false;
      }
    }
  }

  private handleEmailLogin() {
    // Implement email login logic
    setTimeout(() => {
      this.showTwoFactor = true;
      this.isLoading = false;
    }, 1000);
  }

  private handleSchoolLogin() {
    // Implement school login logic
    setTimeout(() => {
      this.router.navigate(['/dashboard']);
      this.isLoading = false;
    }, 1000);
  }

  private handlePhoneLogin() {
    // Implement phone login logic
    setTimeout(() => {
      this.showTwoFactor = true;
      this.isLoading = false;
    }, 1000);
  }

  async loginWithGoogle() {
    try {
      this.isLoading = true;
      this.errorMessage = '';
      await this.authService.loginWithGoogle();
      this.router.navigate(['/dashboard']);
    } catch (error) {
      this.errorMessage = 'Google login failed. Please try again.';
    } finally {
      this.isLoading = false;
    }
  }

  verifyTwoFactor() {
    if (this.twoFactorForm.valid) {
      this.isLoading = true;
      // Simulate 2FA verification
      setTimeout(() => {
        this.multiDeviceAlert = true;
        this.isLoading = false;
      }, 1000);
    }
  }

  togglePasswordVisibility() {
    this.showPassword = !this.showPassword;
  }

  forgotPassword() {
    this.router.navigate(['/auth/forgot-password']);
  }
}
<div class="teacher-login min-h-screen bg-gray-50 flex flex-col items-center justify-center p-4">
  <div class="w-full max-w-md space-y-6 bg-white p-8 rounded-xl shadow-lg">
    <!-- Header -->
    <div class="flex items-center justify-between">
      <button 
        (click)="goBack()"
        class="flex items-center text-gray-600 hover:text-gray-900"
      >
        <i class="material-icons">arrow_back</i>
        Back
      </button>
      <h1 class="text-2xl font-bold text-gray-900">Teacher Login</h1>
    </div>

    <!-- Error Message -->
    <div *ngIf="errorMessage" class="bg-red-50 border border-red-200 p-4 rounded-lg">
      <div class="flex items-center">
        <i class="material-icons text-red-600">error</i>
        <p class="ml-2 text-red-800">{{ errorMessage }}</p>
      </div>
    </div>

    <!-- Multi-device Alert -->
    <div *ngIf="multiDeviceAlert" class="bg-yellow-50 border border-yellow-200 p-4 rounded-lg">
      <div class="flex items-center">
        <i class="material-icons text-yellow-600">warning</i>
        <p class="ml-2 text-yellow-800">You are logged in on another device. Would you like to continue?</p>
      </div>
    </div>

    <!-- Login Form -->
    <ng-container *ngIf="!showTwoFactor; else twoFactorTemplate">
      <!-- Login Method Tabs -->
      <div class="flex space-x-4 border-b border-gray-200">
        <button *ngFor="let method of loginMethods"
          (click)="loginMethod = method.id"
          [class]="loginMethod === method.id ? 
            'pb-2 px-1 border-b-2 border-green-500 text-green-600 font-medium' :
            'pb-2 px-1 text-gray-500 hover:text-gray-700'"
        >
          {{ method.label }}
        </button>
      </div>

      <form [formGroup]="loginForm" (ngSubmit)="onSubmit()" class="space-y-4">
        <ng-container [ngSwitch]="loginMethod">
          
          <!-- Email Login -->
          <ng-container *ngSwitchCase="'email'">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">Email Address</label>
              <div class="relative">
                <i class="material-icons absolute left-3 top-2.5 text-gray-400">mail</i>
                <input
                  type="email"
                  formControlName="email"
                  class="pl-10 w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="your.email@school.edu"
                >
              </div>
            </div>
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">Password</label>
              <div class="relative">
                <i class="material-icons absolute left-3 top-2.5 text-gray-400">key</i>
                <input
                  [type]="showPassword ? 'text' : 'password'"
                  formControlName="password"
                  class="pl-10 w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                >
              </div>
            </div>
          </ng-container>

          <!-- School ID Login -->
          <ng-container *ngSwitchCase="'school'">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">School ID</label>
              <div class="relative">
                <i class="material-icons absolute left-3 top-2.5 text-gray-400">school</i>
                <input
                  type="text"
                  formControlName="schoolId"
                  class="pl-10 w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="Enter your school ID"
                >
              </div>
            </div>
          </ng-container>

          <!-- Phone Login -->
          <ng-container *ngSwitchCase="'phone'">
            <div>
              <label class="block text-sm font-medium text-gray-700 mb-1">Phone Number</label>
              <div class="relative">
                <i class="material-icons absolute left-3 top-2.5 text-gray-400">phone</i>
                <input
                  type="tel"
                  formControlName="phone"
                  class="pl-10 w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="Enter your phone number"
                >
              </div>
            </div>
          </ng-container>
        </ng-container>

        <button
          type="submit"
          [disabled]="loginForm.invalid || isLoading"
          [class.loading]="isLoading"
          class="w-full bg-green-600 hover:bg-green-700 text-white font-medium py-2 px-4 rounded-lg transition-colors"
        >
          {{ loginMethod === 'phone' ? 'Send OTP' : 'Login' }}
        </button>
      </form>

      <div class="text-center">
        <button (click)="forgotPassword()" class="text-blue-600 hover:text-blue-800 text-sm">
          Forgot password?
        </button>
      </div>
    </ng-container>
  </div>
</div>

<ng-template #twoFactorTemplate>
  <form [formGroup]="twoFactorForm" (ngSubmit)="verifyTwoFactor()" class="space-y-4">
    <div class="text-center mb-4">
      <i class="material-icons text-green-500 text-5xl">mail</i>
      <h2 class="text-xl font-semibold">Check your email</h2>
      <p class="text-gray-600">We've sent a verification code to your email</p>
    </div>
    <div>
      <label class="block text-sm font-medium text-gray-700 mb-1">Verification Code</label>
      <input
        type="text"
        formControlName="code"
        class="verification-code w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
        placeholder="Enter 6-digit code"
        maxlength="6"
      >
    </div>
    <button
      type="submit"
      [disabled]="twoFactorForm.invalid || isLoading"
      class="w-full bg-green-600 hover:bg-green-700 text-white font-medium py-2 px-4 rounded-lg transition-colors"
    >
      Verify
    </button>
  </form>
</ng-template>

// src/components/login/teacher/TeacherLogin.tsx
import React, { useState } from 'react';
import { Mail, Key, School, Phone, ArrowLeft, AlertCircle } from 'lucide-react';
import { Alert, AlertDescription } from '../../ui/alert';

const TeacherLogin = () => {
  const [loginMethod, setLoginMethod] = useState('email');
  const [email, setEmail] = useState('');
  const [password, setPassword] = useState('');
  const [schoolId, setSchoolId] = useState('');
  const [phone, setPhone] = useState('');
  const [showTwoFactor, setShowTwoFactor] = useState(false);
  const [twoFactorCode, setTwoFactorCode] = useState('');
  const [multiDeviceAlert, setMultiDeviceAlert] = useState(false);

  const handleLogin = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    // Simulate 2FA trigger
    setShowTwoFactor(true);
  };

  const handleTwoFactorSubmit = (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    // Simulate multi-device detection
    setMultiDeviceAlert(true);
  };

  const renderLoginForm = () => {
    switch (loginMethod) {
      case 'email':
        return (
          <form onSubmit={handleLogin} className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Email Address</label>
              <div className="relative">
                <Mail className="absolute left-3 top-2.5 h-5 w-5 text-gray-400" />
                <input
                  type="email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="pl-10 w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="your.email@school.edu"
                  required
                />
              </div>
            </div>
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Password</label>
              <div className="relative">
                <Key className="absolute left-3 top-2.5 h-5 w-5 text-gray-400" />
                <input
                  type="password"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="pl-10 w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  required
                />
              </div>
            </div>
            <button
              type="submit"
              className="w-full bg-green-600 hover:bg-green-700 text-white font-medium py-2 px-4 rounded-lg transition-colors"
            >
              Login
            </button>
          </form>
        );
      case 'school':
        return (
          <form onSubmit={handleLogin} className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">School ID</label>
              <div className="relative">
                <School className="absolute left-3 top-2.5 h-5 w-5 text-gray-400" />
                <input
                  type="text"
                  value={schoolId}
                  onChange={(e) => setSchoolId(e.target.value)}
                  className="pl-10 w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="Enter your school ID"
                  required
                />
              </div>
            </div>
            <button
              type="submit"
              className="w-full bg-green-600 hover:bg-green-700 text-white font-medium py-2 px-4 rounded-lg transition-colors"
            >
              Continue
            </button>
          </form>
        );
      case 'phone':
        return (
          <form onSubmit={handleLogin} className="space-y-4">
            <div>
              <label className="block text-sm font-medium text-gray-700 mb-1">Phone Number</label>
              <div className="relative">
                <Phone className="absolute left-3 top-2.5 h-5 w-5 text-gray-400" />
                <input
                  type="tel"
                  value={phone}
                  onChange={(e) => setPhone(e.target.value)}
                  className="pl-10 w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
                  placeholder="Enter your phone number"
                  required
                />
              </div>
            </div>
            <button
              type="submit"
              className="w-full bg-green-600 hover:bg-green-700 text-white font-medium py-2 px-4 rounded-lg transition-colors"
            >
              Send OTP
            </button>
          </form>
        );
      default:
        return null;
    }
  };

  const renderTwoFactor = () => (
    <form onSubmit={handleTwoFactorSubmit} className="space-y-4">
      <div className="text-center mb-4">
        <Mail className="mx-auto h-12 w-12 text-green-500 mb-2" />
        <h2 className="text-xl font-semibold">Check your email</h2>
        <p className="text-gray-600">We've sent a verification code to your email</p>
      </div>
      <div>
        <label className="block text-sm font-medium text-gray-700 mb-1">Verification Code</label>
        <input
          type="text"
          value={twoFactorCode}
          onChange={(e) => setTwoFactorCode(e.target.value)}
          className="w-full p-2 border border-gray-300 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-blue-500"
          placeholder="Enter 6-digit code"
          maxLength={6}
          required
        />
      </div>
      <button
        type="submit"
        className="w-full bg-green-600 hover:bg-green-700 text-white font-medium py-2 px-4 rounded-lg transition-colors"
      >
        Verify
      </button>
    </form>
  );

  return (
    <div className="min-h-screen w-screen bg-gray-50 flex flex-col items-center justify-center p-4">
      <div className="w-full max-w-md mx-auto space-y-6 bg-white p-8 rounded-xl shadow-lg">
        <div className="flex items-center justify-between">
          <button 
            onClick={() => window.history.back()}
            className="flex items-center text-gray-600 hover:text-gray-900"
          >
            <ArrowLeft className="h-5 w-5 mr-1" />
            Back
          </button>
          <h1 className="text-2xl font-bold text-gray-900">Teacher Login</h1>
        </div>

        {multiDeviceAlert && (
          <Alert className="bg-yellow-50 border-yellow-200">
            <AlertCircle className="h-4 w-4 text-yellow-600" />
            <AlertDescription className="text-yellow-800">
              You are logged in on another device. Would you like to continue?
            </AlertDescription>
          </Alert>
        )}

        {!showTwoFactor ? (
          <>
            <div className="flex space-x-4 border-b border-gray-200">
              {[
                { id: 'email', label: 'Email' },
                { id: 'school', label: 'School ID' },
                { id: 'phone', label: 'Phone' }
              ].map((method) => (
                <button
                  key={method.id}
                  onClick={() => setLoginMethod(method.id)}
                  className={`pb-2 px-1 ${
                    loginMethod === method.id
                      ? 'border-b-2 border-green-500 text-green-600 font-medium'
                      : 'text-gray-500 hover:text-gray-700'
                  }`}
                >
                  {method.label}
                </button>
              ))}
            </div>

            {renderLoginForm()}

            <div className="text-center">
              <button className="text-blue-600 hover:text-blue-800 text-sm">
                Forgot password?
              </button>
            </div>
          </>
        ) : (
          renderTwoFactor()
        )}
      </div>
    </div>
  );
};

export default TeacherLogin;
